// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  var RedisStore, app, bodyParser, config, cookieParser, csrf, errorHandlers, express, flash, log, partials, routes, session, util;

  express = require('express');

  app = express();

  errorHandlers = require('./middleware/errorhandlers');

  routes = require('./routes');

  log = require('./middleware/logger');

  partials = require('express-partials');

  cookieParser = require('cookie-parser');

  session = require('express-session');

  RedisStore = require('connect-redis')(session);

  bodyParser = require('body-parser');

  csrf = require('csurf');

  util = require('./middleware/utilities');

  flash = require('connect-flash');

  config = require('./config');

  app.set('view engine', 'ejs');

  app.set('view options', {
    defaultLayout: 'layout'
  });

  app.use(partials());

  app.use(log.logger);

  app.use(express["static"](__dirname + '/static'));

  app.use(cookieParser(config.secret));

  app.use(session({
    secret: config.secret,
    saveUninitialized: true,
    resave: true,
    store: new RedisStore({
      url: 'redis://localhost'
    })
  }));

  app.use(bodyParser.json());

  app.use(bodyParser.urlencoded({
    extended: false
  }));

  app.use(csrf());

  app.use(util.csrf);

  app.use(util.authenticated);

  app.use(flash());

  app.use(util.templateRoutes);

  app.get('/', routes.index);

  app.get(config.routes.login, routes.login);

  app.post(config.routes.login, routes.loginProcess);

  app.get('/chat', [util.requireAuthentication], routes.chat);

  app.get(config.routes.logout, routes.logOut);

  app.use(errorHandlers.error);

  app.use(errorHandlers.notFound);

  app.listen(config.port);

  console.log('App running on port 3000');

}).call(this);

//# sourceMappingURL=app.js.map
