// Generated by CoffeeScript 1.10.0
(function() {
  'use strict';
  var RedisStore, app, cookieParser, errorHandlers, express, log, partials, routes, session;

  express = require('express');

  app = express();

  errorHandlers = require('./middleware/errorhandlers');

  routes = require('./routes');

  log = require('./middleware/logger');

  partials = require('express-partials');

  cookieParser = require('cookie-parser');

  session = require('express-session');

  RedisStore = require('connect-redis')(session);

  app.set('view engine', 'ejs');

  app.set('view options', {
    defaultLayout: 'layout'
  });

  app.use(log.logger);

  app.use(express["static"](__dirname + '/static'));

  app.use(cookieParser('secret'));

  app.use(session({
    secret: 'secret',
    saveUninitialized: true,
    resave: true,
    store: new RedisStore({
      url: 'redis://localhost'
    })
  }));

  app.use(partials());

  app.get('/', routes.index);

  app.get('/login', routes.login);

  app.post('/login', routes.loginProcess);

  app.get('/chat', routes.chat);

  app.get('/error', function(req, res, next) {
    next(new Error('MY bad!'));
  });

  app.use(errorHandlers.notFound);

  app.use(errorHandlers.error);

  app.listen(3000);

  console.log('App running on port 3000');

}).call(this);

//# sourceMappingURL=app.js.map
