// Generated by CoffeeScript 1.10.0
(function() {
  var config;

  config = {
    port: 3000,
    secret: 'secret',
    redisUrl: 'redis://localhost',
    routes: {
      login: '/login',
      logout: '/logout'
    }
  };

  module.exports = config;

}).call(this);

//# sourceMappingURL=config.js.map
