// Generated by CoffeeScript 1.10.0
(function() {
  var io;

  io = require('socket.io').listen(4000);

  io.sockets.on('connection', function(socket) {
    socket.username = data.username;
    return socket.broadcast.emit('join', {
      username: data.username,
      socket: socket.id
    });
  });

  socket.on('ping', function() {
    return socket.broadcast.emit('ping', {
      username: socket.username
    });
  });

  socket.on('privatePing', function(data) {
    return io.sockets.connected[data.socket].emit('ping', {
      username: socket.username,
      priv: true
    });
  });

}).call(this);

//# sourceMappingURL=namespace.js.map
