// Generated by CoffeeScript 1.10.0
(function() {
  var io;

  io = require('socket.io').listen(4000);

  io.of('/vip').on('connection', function(socket) {
    socket.on('join', function(data) {});
    socket.username = data.username;
    socket.broadcast.emit('join', {
      username: data.username,
      socket: socket.id
    });
    socket.on('ping', function() {
      return socket.broadcast.emit('ping', {
        username: socket.username
      });
    });
    return socket.on('privatePing', function(data) {
      return io.of('/vip').connected[data.socket].emit('ping', {
        username: socket.username,
        priv: true
      });
    });
  });

  io.of('/vip');

}).call(this);

//# sourceMappingURL=namespace.js.map
