// Generated by CoffeeScript 1.10.0

/**
 * Routes
 */

(function () {
	var chat, index, login, loginProcess;

	index = function (req, res) {
		res.clearCookie('Index Cookie');
		res.render('index', {
			layout: 'layout',
			title: 'Home',
			cookie: JSON.stringify(req.cookies),
			session: JSON.stringify(req.session)
		});
	};

	login = function (req, res) {
		res.render('login', {
			title: 'Login'
		});
	};

	loginProcess = function (req, res) {
		res.redirect('/');
	};

	chat = function (req, res) {
		res.render('chat', {
			title: 'Chat'
		});
	};

	'use strict';

	module.exports.index = index;

	module.exports.login = login;

	module.exports.loginProcess = loginProcess;

	module.exports.chat = chat;

}).call(this);

//# sourceMappingURL=index.js.map
