// Generated by CoffeeScript 1.10.0

/**
 * Routes
 */

(function () {
  var chat, index, login, loginProcess, util;

  util = require('../middleware/utilities');

  index = function (req, res) {
    res.render('index', {
      title: 'Home'
    });
  };

  login = function (req, res) {
    res.render('login', {
      title: 'Login'
    });
  };

  loginProcess = function (req, res) {
    var isAuth;
    isAuth = util.auth(req.body.username, req.body.password, req.session);
    if (isAuth) {
      res.redirect('/chat');
    } else {
      res.redirect('/login');
    }
  };

  chat = function (req, res) {
    res.render('chat', {
      title: 'Chat'
    });
  };

  'use strict';

  module.exports.index = index;

  module.exports.login = login;

  module.exports.loginProcess = loginProcess;

  module.exports.chat = chat;

}).call(this);

//# sourceMappingURL=index.js.map
