// Generated by CoffeeScript 1.10.0
(function() {
  var io;

  io = require('socket.io').listen(4000);

  io.sockets.on('connection', function(socket) {
    socket.on('join', function(data) {
      socket.broadcast.emit('userJoined', data);
      return socket.username = data.username;
    });
    socket.on('ping', function(data, done) {
      io.sockets.emit('ping', {
        username: socket.username
      });
      return done('ack');
    });
    return socket.on('disconnect', function() {
      return socket.broadcast.emit('userDisconnect', {
        username: socket.username
      });
    });
  });

}).call(this);

//# sourceMappingURL=firstsocketapp.js.map
