// Generated by CoffeeScript 1.10.0
(function() {
  var io;

  io = require('socket.io').listen(4000);

  io.sockets.on('connection', function(socket) {
    socket.on('join', function(data) {
      socket.username = data.username;
      socket.join(data.room);
      return socket.broadcast.to(data.room).emit('join', {
        username: data.username,
        socket: socket.id,
        room: data.room
      });
    });
    socket.on('ping', function(data) {
      return socket.broadcast.to(data.room).emit('ping', {
        username: socket.username,
        room: data.room
      });
    });
    return socket.on('privatePing', function(data) {
      return io.sockets.connected[data.socket].emit('ping', {
        username: socket.username,
        priv: true,
        room: data.room
      });
    });
  });

}).call(this);

//# sourceMappingURL=rooms.js.map
